cuda_device: 0
project: "extracting_moore"
nb_workers: 0                 # number of workers for dataloader
reps: 1                       # number of repetitions
pos_embeddings: "rotary"      # type of positional embeddings
l: 32                         # length of sequences
N: 10000                      # number of sequences
method: "positive_only"       # method of sampling dataset
no_dups: True                 # no duplicates in dataset
dev: False                    # run in dev mode
run_id: Null                  # run id to extract automata; Trains new if None
seed: 1337